### ISSUE TITLE
Enhance .lang syntax

### ISSUE THREAD

**Issue by mouse0w0** [UnknownDomainGames/PanguEngine#91]
https://github.com/UnknownDomainGames/PanguEngine/blob/81b8276f1773d35c56edf715fdbff7dc01854351/game-engine/src/main/java/engine/client/i18n/LocaleManager.java#L82-L90

Maybe we should use the `Properties` class to load the language file, or a similar way.

**Comment by xtexx** [comment]
We have almost implemented most of the functions of Properties (except XML format), including comments and empty lines.

I think this loader is better in performance because the `Properties` class has some other features such as: use `:` to instead `=`, ignoring ` `, `\t`, `\f` near the `=`, and use escapes such as `\=`, `\:`, `\ `, `\TAB` and `\form feed`

**Comment by mouse0w0** [comment]
https://github.com/UnknownDomainGames/PanguEngine/blob/64c261fd9d6658788d990ae09e6dcfecf1be5857/game-engine/src/main/java/engine/client/i18n/LocaleManager.java#L108-L112

When you're working for this issue, you can add a reference to the issue in the commit message (like `feat: do something (#91)`).

I wanna:
1. Throw an exception with file name and line number, when the line not found the `=` equals seperator. 
2. Support to use escape characters.
3. `line.isEmpty()` cannot check the line that contains only whitespace characters.

**Comment by xtexx** [comment]
Features:

1. [x] Human friendly exception messages
2. [x] Escape characters
        - [Java Language Specification 11 3.3](https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.3)
        - [Java Language Specification 11 3.10.6](https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.10.6)
3. [x] Comment & empty lines
4. [x] Trim leading spaces

**Comment by xtexx** [comment]
Solved
